### ISSUE TITLE
Error $ make android on Ubuntu 18.04

### ISSUE THREAD

**Issue by ekorudi** [signalapp/ringrtc#6] opened 2020-01-25 06:55 UTC
```
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-n332890-c2443155-1.tgz .......... Done.
Hook 'vpython src/tools/clang/scripts/update.py' took 46.36 secs
________ running 'vpython src/build/util/lastchange.py -o src/build/util/LASTCHANGE' in '/ok/dev/ringrtc-25jan/out/webrtc'
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s src/buildtools/linux64/clang-format.sha1' in '/ok/dev/ringrtc-25jan/out/webrtc'
0> Downloading src/buildtools/linux64/clang-format...
Downloading 1 files took 4.835494 second(s)
________ running 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-chained-origins-trusty.tgz.sha1' in '/ok/dev/ringrtc-25jan/out/webrtc'
Failed to fetch file gs://chromium-instrumented-libraries/92ab0ac3915bc2b50e6a8d7a990522d7355d1ef0 for src/third_party/instrumented_libraries/binaries/msan-chained-origins-trusty.tgz. [Err: [E2020-01-25T13:39:42.185840+07:00 25562 0 annotate.go:241] original error: no such package
[E2020-01-25T13:39:42.186337+07:00 25562 0 annotate.go:241] 
[E2020-01-25T13:39:42.186387+07:00 25562 0 annotate.go:241] goroutine 38:
[E2020-01-25T13:39:42.186414+07:00 25562 0 annotate.go:241] #0 go.chromium.org/luci/cipd/client/cipd/client.go:1684 - cipd.humanErr()
[E2020-01-25T13:39:42.186442+07:00 25562 0 annotate.go:241] #1 go.chromium.org/luci/cipd/client/cipd/client.go:741 - cipd.(*clientImpl).ResolveVersion()
[E2020-01-25T13:39:42.186472+07:00 25562 0 annotate.go:241] #2 go.chromium.org/luci/cipd/client/cipd/resolver.go:176 - cipd.(*Resolver).resolveVersion.func1()
[E2020-01-25T13:39:42.186530+07:00 25562 0 annotate.go:241] #3 go.chromium.org/luci/common/sync/promise/promise.go:84 - promise.(*Promise).runGen()
[E2020-01-25T13:39:42.186562+07:00 25562 0 annotate.go:241] #4 runtime/asm_amd64.s:1357 - runtime.goexit()

```

**Comment by inthewaves** [comment] 2020-01-25 07:59
What's your Python version (what does `python -V` give you?) If you're using Python 3, try Python 2.7.

**Comment by ekorudi** [comment] 2020-01-25 10:10
$ python -V
Python 2.7.15rc1

**Comment by ekorudi** [comment] 2020-01-25 10:10
> What's your Python version (what does `python -V` give you?) If you're using Python 3, try Python 2.7.

$ python -V
Python 2.7.15rc1

**Comment by CatsNipYummy** [comment] 2020-02-29 01:12
Why doesn't the fetch work with python3?

**Comment by jim-signal** [comment] 2020-04-25 05:03
@ekorudi is this still an issue for you? Since your OP, we have changed the build process slightly. However, the initial step still involves downloading WebRTC dependencies using the chromium depot_tools.

I think they use their own copy of python, and this page says to make sure that the depot_tools is in the front of of your path: https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html

Other than that, I occasionally see sporadic vpython issues due to connectivity problems, but another try usually works (i.e. nothing reproducible for me).

**Comment by jim-signal** [comment] 2020-05-16 00:13
Closing. If this is still a problem, please use the latest version of RingRTC and open a new issue.

**Closed by jim-signal** 2020-05-16 00:13 UTC
