### ISSUE TITLE
Cannot Build RingRTC with Software Encoding/Decoding, also SW Encoding/Decoding RingRTC

### ISSUE THREAD

**Issue by apptester235** [signalapp/ringrtc#10] opened 2020-03-30 18:36 UTC
I was trying to build RingRTC with Software encoding, only, and this error had popped up: 

../../../src/webrtc/src/ringrtc/android/api/org/signal/ringrtc/CallManager.java:765: error: constructor SoftwareVideoEncoderFactory in class SoftwareVideoEncoderFactory cannot be applied to given types;
      VideoEncoderFactory encoderFactory = new SoftwareVideoEncoderFactory(eglBase.getEglBaseContext(),
                                           ^
  required: no arguments
  found: Context,boolean,boolean
  reason: actual and formal argument lists differ in length
1 error

The biggest problem with the whole Signal App is that many phones such as Samsung or Huawei phones, and many other types, have a big issue whilst they use the camera, and especially when a person is trying to video call, the phone would just go dark and so the receiver of the call would just see a black screen. 

Here is the issue tracker:
https://github.com/signalapp/Signal-Android/issues/8685

And one of the developers at jitsi-meet, saghul, Had suggested that Signal should use Software encoding to solve the issue. With this: 

https://github.com/signalapp/Signal-Android/issues/8685#issuecomment-589550198
Here: https://github.com/signalapp/ringrtc/blob/d816012799dfacf9c9b69f30b7cf2bdcac57b78c/src/android/api/org/signal/ringrtc/CallManager.java#L762 replace DefaultVideoEncoderFactory with SoftwareVideoEncoderFactory (it takes no parameters).

There has been an update as many users on the  jitsi meet app were having issues, they also had made Decoding and Encoding using Software only: 
https://github.com/jitsi/jitsi-meet/commit/b0e7471a8323c3baf8350bf7a0154af378d3e71f
I have also tested the app, and it has fixed the issue of the camera not working. 

Is there a way to switch RingRTC to use Software encoding or decoding?, and so I would be able to build the app, with such a feature built in and so test out if the Video calling has been fixed. And so if it does work then could it be pushed to the main repo which would fix a lot of people phones which have been experiencing this issue for months now.

If anyone would be able to help me out with Signal having Software encoding and decoding to fix this issue I have been having for a very long time now, your help would be greatly appreciated.

**Comment by peter-signal** [comment] 2020-03-30 21:20
Thank you for letting us know you are running into this.

It would be useful to know what phone model you are on and if you are running into problems with the encoder, decoder, or both.  Could you tell us what model you can reproduce this problem on?

Changing those two lines to be this:

      VideoEncoderFactory encoderFactory = new SoftwareVideoEncoderFactory();
      VideoDecoderFactory decoderFactory = new SoftwareVideoDecoderFactory();

Should have the effect you want.

But if we added that as a setting, it would be difficult for most users to know that trying that setting would help.  Ideally, we could have Signal automatically adapt based on the model number or the behavior of the encoder/decoder, but neither of those mechanisms are easy to implement.

Are you able to build with those two lines?  If so, could you try just one or the other and let us know which one helps (encoder, decoder, or both)?

**Comment by apptester235** [comment] 2020-03-30 21:57
Thank you for the quick reply, 
I'm experiencing this issue on a samsung s6 G920F (Europe) with an Exynos 7420, in the issue tracker above there has been a lot of people mentioning their phone specifications as well and they all have been experiencing the same issue, some people have said here:
https://community.signalusers.org/t/video-call-freezes-for-other-user/7022/3
that is has to do with the Exynos chipset and it causing the issues. But many phones which have been affected by this issue have such chip set in place, so that could be the cause. 

As for building, 
This is the line I changed: 
VideoEncoderFactory encoderFactory = new DefaultVideoEncoderFactory(eglBase.getEglBaseContext(), 

And I also had added these two lines as it did not recognize the Software argument. 

import org.webrtc.SoftwareVideoDecoderFactory;
import org.webrtc.SoftwareVideoEncoderFactory;

 It had come up with this issue when building: 

../../../src/webrtc/src/ringrtc/android/api/org/signal/ringrtc/CallManager.java:765: error: constructor SoftwareVideoEncoderFactory in class SoftwareVideoEncoderFactory cannot be applied to given types;
VideoEncoderFactory encoderFactory = new SoftwareVideoEncoderFactory(eglBase.getEglBaseContext(),
^
required: no arguments
found: Context,boolean,boolean
reason: actual and formal argument lists differ in length
1 error

This is a commit had been implemented into Jitsi Meet and they have switched to Software Encoding and decding due to the crashes on Samsung and Huawei devices: 
https://github.com/jitsi/jitsi-meet/commit/b0e7471a8323c3baf8350bf7a0154af378d3e71f

The changes which you have proposed, do not have the extra arguments at the end and so they could work, in the build. 
I will try the solution which you have proposed and I will report back on issues or the results I got from building it at the nearest possible time for me. 

Thank you for responding once again, really would want to fix this issue.

**Comment by apptester235** [comment] 2020-03-31 11:42
If the RingRTC library does get built, how will I be able to integrate the new Files with Software encoding or decoding or both, into Signal android?

**Comment by peter-signal** [comment] 2020-03-31 18:31
Yeah, we need to update our documentation :).

If you can build Signal-Android, add these steps:

1.  Build RingRTC like this:

OVERRIDE_VERSION=1.0.0-test ./bin/build-aar --install-local

2.  Change Signal-Android's app/build.gradle to point at 1.0.0-test instead of 1.0.0 or 1.1.0 or 1.2.0 or whatever it points at.

3.  Then do this step before building Signal-Android:

 ./gradlew -q calculateChecksums

4.  Finally, build Signal-Android like normal:

./gradlew assemblePlayDebug


If you can't built Signal-Android yet, start here: https://github.com/signalapp/Signal-Android/wiki/How-to-build-Signal-from-the-sources

**Comment by apptester235** [comment] 2020-03-31 20:04
> 1. Build RingRTC like this:
> OVERRIDE_VERSION=1.0.0-test ./bin/build-aar --install-local

I have inputted that into my terminal, in the root of RingRTC, and it gives me this output:
./bin/build-aar: 17: .: : not found

And it just fails no building

**Comment by peter-signal** [comment] 2020-03-31 21:08
Are you in the directory where RingRTC is checked out?  (for example ~/src/ringrtc?)

**Comment by apptester235** [comment] 2020-03-31 21:22
I had git cloned RingRTC into home folder, which means its  ~/RingRTC/, and that is where I had executed the command, in ~/RingRTC:
 OVERRIDE_VERSION=1.0.0-test ./bin/build-aar --install-local

**Comment by jim-signal** [comment] 2020-03-31 21:39
Can you try to run this first:
`./bin/prepare-workspace android`

The error from build-aar: 17 looks like it is missing the NDK. Normally, this would all be set if you first ran `make android`, but running the prepare command then build-aar is basically the same.

**Comment by apptester235** [comment] 2020-04-01 12:32
I have manged to execute OVERRIDE_VERSION=1.0.0-test ./bin/build-aar –install-local. 

When I executed the command this is what I got: 

server@buildserver:~/ringrtc$ OVERRIDE_VERSION=1.0.0-test ./bin/build-aar --install-local

BUILD SUCCESSFUL in 2s
2 actionable tasks: 2 executed
I:
Version           : 1.0.0-test
Architectures     : ['arm', 'arm64', 'x86', 'x64']
Debug Build       : False
Release Build     : False
Build Directory   : /home/server/ringrtc/out
Stripped Libraries: True

(The end of the build, where it says that it has completed, not the full log) 

Now where would I be able to find the aar files which I have generated, and how will I be able to point the Signal android gradle to the specific files, so that they can be used whilst build Signal android, and not the standard RingRTC library?

**Comment by jim-signal** [comment] 2020-04-01 21:29
The install-local process should put the artifacts somewhere like `~/.m2/repository/org/signal/ringrtc-android/`.

Now you need to switch over to Signal-Android and do steps 2, 3, and 4 from https://github.com/signalapp/ringrtc/issues/10#issuecomment-606797700 above. It should pick up your local copy when it assembles the APK.

**Comment by apptester235** [comment] 2020-04-01 21:53
Hello,
I cannot find the artifacts that you are talking about
And how would I go about doing step 2, from #10 (comment) above if I do find the artifacts?

**Comment by apptester235** [comment] 2020-04-03 21:53
I have even install maven, and have that directory ~/.m2/repository/org, but no aars are being built when I execute the command:
OVERRIDE_VERSION=1.0.0-test ./bin/build-aar --install-local
For some weird reason, have searched for .aar files and only get: 

curve25519-android-0-5-0.aar
signal-metadata-android-0.1.0.aar
signal-protocol-android-2-0-1.aar
signal-service-android-2.15.3.aar

All these files are found in my android-deps folder in ringrtc, but still no ringrtc.aar file, to be found anywhere. And signal does not appear in my maven directory.

**Comment by cbrune-signal** [comment] 2020-04-03 23:25
Howdy @apptester235 -- I think I might know what's wrong.

Make sure you have a `ringrtc/publish/android/local.properties` file, with contents something like this:

```
ndk.dir=/home/curt/Android/Sdk/ndk-bundle
sdk.dir=/home/curt/Android/Sdk
```

**Comment by apptester235** [comment] 2020-04-04 12:10
I have done as you said, had to install Android Studio, with that it had installed the directories, except for the NDK, which I had used the SDK Manager, to install. 

I had re ran the  ./bin/prepare-workspace android and OVERRIDE_VERSION=1.0.0-test ./bin/build-aar --install-local commands 
But still no aar files have been made and the same files have popped up when I had searched for .aar files, which are: 

curve25519-android-0-5-0.aar
signal-metadata-android-0.1.0.aar
signal-protocol-android-2-0-1.aar
signal-service-android-2.15.3.aar

Here is a log of what I had seen in the terminal when I had executed both of the commands:
https://github.com/apptester235/RingRTC-Build-Logs/blob/master/log.txt
Just wanted to submit it so that the issue can be spotted and solved. If there is anymore information that you want feel free to ask.

**Comment by apptester235** [comment] 2020-04-05 16:21
I did this command, changed the directory. 
server@server:~/ringrtc$ OVERRIDE_VERSION=1.0.0-test ./bin/build-aar --verbose --install-local --install-dir ~/home/

It then generated these files, these are not .aar files but .so files and .jar files also. 
server@server:~/home$ tree 1.0.0-test/
1.0.0-test/
└── android
    ├── debug
    │   └── libs
    │       ├── arm64-v8a
    │       │   ├── libringrtc_rffi.so
    │       │   └── libringrtc.so
    │       ├── armeabi-v7a
    │       │   ├── libringrtc_rffi.so
    │       │   └── libringrtc.so
    │       ├── libringrtc.jar
    │       ├── libwebrtc.jar
    │       ├── x86
    │       │   ├── libringrtc_rffi.so
    │       │   └── libringrtc.so
    │       └── x86_64
    │           ├── libringrtc_rffi.so
    │           └── libringrtc.so
    └── release
        └── libs
            ├── arm64-v8a
            │   ├── libringrtc_rffi.so
            │   └── libringrtc.so
            ├── armeabi-v7a
            │   ├── libringrtc_rffi.so
            │   └── libringrtc.so
            ├── libringrtc.jar
            ├── libwebrtc.jar
            ├── x86
            │   ├── libringrtc_rffi.so
            │   └── libringrtc.so
            └── x86_64
                ├── libringrtc_rffi.so
                └── libringrtc.so

This was the build log:
https://github.com/apptester235/RingRTC-Build-Logs/blob/master/log2

Where these the files that were meant to be built from the start or?

**Comment by jim-signal** [comment] 2020-04-06 06:39
Your log seems okay, and yes, those are the files and they are supposed to be put in to an AAR file by using the build-aar script. Your commands seem correct. Are you sure you have no ~/.m2 directory? build-aar invokes gradle which is placing it there. Unless you have some other mapping for this like an M2_HOME environment variable?

**Comment by apptester235** [comment] 2020-04-06 07:08
The only reason I have generated the ~/.m2 directory was due to installing maven and using it to generated another project, but it was not generated when I had execute the build-aar scipt.

**Comment by jim-signal** [comment] 2020-04-06 16:52
You can try running your build-aar command with the option:
`--extra-gradle-args=--debug`

You don't need to upload it. You should see something like this in there:
```
...
...Deploying to file://home/your_username/.m2/repository
...Uploading: org/signal/ringrtc-android/1.0.0-test/ringrtc-android-1.0.0-test.aar to repository remote at file://home/your_username/.m2/repository
...
```

Do you see any issues there?

**Comment by apptester235** [comment] 2020-04-07 07:06
I don't see the part which you specified in the log, just to make it easier to diagnose the Log was attached. 

Command:
OVERRIDE_VERSION=1.0.0-test ./bin/build-aar --install-local --extra-gradle-args=--debug

And Log:
https://github.com/apptester235/RingRTC-Build-Logs/blob/master/log3.txt

**Comment by jim-signal** [comment] 2020-04-07 17:03
Your build log is missing some things, but it is hard to track down exactly what... Although the recommendation above to set the local.properties file should work, sometimes setting the environment variables `ANDROID_HOME` and `NDK_HOME` will help. Can you set or make sure they are set? For example, if using a recent SDK:

```
export ANDROID_HOME=/home/signal/Android/Sdk
export NDK_HOME=/home/signal/Android/Sdk/ndk/21.0.6113669
```

Have you already verified that you can build the Signal-Android app itself without changing RingRTC? When setting up a new build machine, we would make sure that is all running smoothly and then add the Rust and WebRTC parts.

https://github.com/signalapp/Signal-Android/wiki/How-to-build-Signal-from-the-sources

**Comment by apptester235** [comment] 2020-04-07 17:45
I had added the changes you requested: 
export ANDROID_HOME=/home/signal/Android/Sdk
export NDK_HOME=/home/signal/Android/Sdk/ndk/21.0.6113669
into the local.properaties file in RingRTC no aac files were generated once again. 

But started to build Signal-Android, it failed and this is what it said: 
https://github.com/apptester235/Signal-Android-Build-Logs/blob/master/log4.txt

**Comment by apptester235** [comment] 2020-04-09 14:49
I was not able to execute the command in the terminal and so build it through that but I was able to import the project into android studios through git, and build it without any errors and so got these files generated:
└── debug
    ├── output.json
    ├── Signal-play-arm64-v8a-debug-4.58.5.apk
    ├── Signal-play-armeabi-v7a-debug-4.58.5.apk
    ├── Signal-play-universal-debug-4.58.5.apk
    ├── Signal-play-x86_64-debug-4.58.5.apk
    └── Signal-play-x86-debug-4.58.5.apk
These is the version of the Signal Android app without the modified RignRTC library just stock, is their a way to make the RingRTC library in Android studio rather than execute the command through the terminal?

**Comment by jim-signal** [comment] 2020-04-10 06:06
Hi, the project is not setup to work with Android Studio. We will be looking to update our build documentation as we update our build environment. Maybe a setting or dependency slipped away somehow.

In the meantime, since you have built Signal-Android, you might want to try the RingRTC 1.3.0 release. This brings WebRTC 4044 in, which had adjusted some of the VP8 video encoder code. In our testing, it seemed more stable, especially with an S7 device we got in order to try to reproduce the problems mentioned in your first post. It hasn't shipped yet in the client, but hopefully it will be possible to update to it with your build. Here would be the steps (all from within Android Studio):

1. Open the app/build.gradle file, find the string 'org.signal:ringrtc-android:1.2.0' and replace with ''org.signal:ringrtc-android:1.3.0'. All you are doing here is updating the version to **1.3.0**. If you are using the latest (or very recent) version, it should have been using 1.2.0.

2. Open the app/witness-verifications.gradle file and find the same string, 'org.signal:ringrtc-android:1.2.0'. Set that section to be this instead:

```
        ['org.signal:ringrtc-android:1.3.0',
         '8f81aea49d13653da82c5737684ddeaf08d6c54a5a44096b8d49ca9270bda24e'],
```
This sets the checksum so it can be verified when downloading/loading the dependency.

3. Now build as usual. I would do **"Build->Clean Project"** first, then **"Make Project"**, and then **Run** or Debug on your device. This combination always gets me a good new build if only updating the dependencies.

Please let us know your results. Thanks for your help!

**Comment by apptester235** [comment] 2020-04-10 08:13
I was able to build the Signal Android with RingRTC 1.3.0, but still experience the same problem as before and always have, a person calls or the user calls, it freezes at random times maybe a few seconds after the call has started or a few minutes, and even if you retry the call it freezes again, so even with the new updates it does nothing and still experience the same issues. 

The S7 device which you have mentioned is a Samsung S7 right?, depending on where you bought the phone will depend on the Chipset, I'm from Europe and so most of the phones here have an Exynos chipset in America the phone would have Qualcomm or a Snapdragon chipset. And so I am experiencing this problem as many others in the community when they use this app and they do have a certain Exynos chipset. Not all but most of the S series samsung phone do have this problem with that particular Chipset and so this problem has been seen or wide spread due to the variations in chipsets. 

With the changes, constant updates and trying I was not able to build the modified RignRTC library with Software decoding and or encoding aar files, and so as you have as working build environment would you be able to build the aar files with such changes, upload them here, then instruct me how to use them in the android signal build and so finally be able to build it. 

I just want to see if Software decoding and encoding truly does help and solve the issue this app have been having for months now and it has affected many people in the community which are unable to securely have video calls, which is the whole point of using such an app. 

If I am able to build the app with the aar that you have generated I would be able to test it on my phone, and see if it fixes it. And so then work towards integrating Software encoding and or decoding into the future releases of signal, so that this fix can be persistent in the future releases of the Android app.

**Comment by apptester235** [comment] 2020-04-10 20:41
I have installed a clean installation of Ubuntu 18.04.04, followed the build guide (https://github.com/signalapp/ringrtc/blob/master/BUILDING.md) as it is written, there are some tweaks that had to be done like installing python, python 2.7, curl and git. Also Chromium depot_tools used a different style of the command for it to work, I had also installed Android studio and had went to the SDK manager installed the other packages which have been described (NDK, LLDB, and SDK Tools options.). 

It still behaves exactly the same way that it did before, downloads everything, builds every last bit of it, says it is complete and then search here, "out/<release|debug>/ringrtc-android<-debug>-<version>.aar" nothing, does not exist, the only 4 .aar files are these: 

> curve25519-android-0-5-0.aar
> signal-metadata-android-0.1.0.aar
> signal-protocol-android-2-0-1.aar
> signal-service-android-2.15.3.aar

No ringrtc.aar to be seen anywhere, not even a .m2 directory at the home directory was generated when I ran the install-local command, Behaves exactly the same way that is has before, in the end no .aar files are generated and you are just left with https://github.com/signalapp/ringrtc/issues/10#issuecomment-609442391 this as described above.

**Comment by apptester235** [comment] 2020-04-15 08:45
I have generated the .aar file and how do I now use the newly generated .aar file into a new Signal android build?

**Comment by ChooseL1fe** [comment] 2020-04-15 20:06
You can add it to your local maven repo. You also need to add .so files to AndroidSignal jni folder and update witness-verifications.gradle (just clean its content and run ./gradlew calculateChecksums). should work

**Comment by jim-signal** [comment] 2020-04-16 00:40
It is great to hear that you got the aar! Did it go to the .m2 directory? If so, then all I do is change the app/build.gradle to refer to that that file _instead_ of the one already there. @peter-signal(https://github.com/signalapp/ringrtc/issues/10#issuecomment-606797700) and @ChooseL1fe described this and then doing the checksum step. I also remove the old value from the witness-verifications.gradle file first though. Finally, you can build with gradle or Android Studio and you should end up with an APK.

If there was any specific step you can share to get the aar file, please do.

**Comment by jim-signal** [comment] 2020-04-25 04:51
FWIW, we got a Samsung S7 with the Exynos SoC and reproduced the issue. A fix using the method you referenced for specific known devices is in our v2.0.0 release. It may take a week or two to get in to the Android client. Hopefully this will help close the issue.

**Comment by apptester235** [comment] 2020-04-25 08:41
Thank you for implementing the fix, when the files get uploaded onto the mvnrepository, I for sure will try to build the android app with the new updates and see if it does fix the issue which I have been experiencing on my Samsung s6 and I will report back, after testing it.

**Comment by apptester235** [comment] 2020-04-28 11:05
What are the results of:
`./gradlew -q calculateChecksums`
For ringrtc 2.0.0, so that I can put in the right checksum into my app/witness-verifications.gradle, which would enable me to build signal android and test?

**Comment by apptester235** [comment] 2020-04-28 14:47
I was able to calculate the checksum added the ringrtc 2.0 but had met with an build error, this is the link to the log: 
https://github.com/apptester235/android-build/blob/master/log1

**Comment by jim-signal** [comment] 2020-04-28 16:37
With the 2.0 release, some APIs changed in our library, so it will take a short time, maybe a week or two, for the Android client to get updated...

**Comment by jim-signal** [comment] 2020-05-03 01:00
Hi @apptester235 you can try RingRTC v1.3.3: 'org.signal:ringrtc-android:1.3.3'

This one has the fix. The 2.x releases may take a while to reach production clients.

**Comment by apptester235** [comment] 2020-05-03 15:31
Hello, 

I have built and tested RingRTC 1.3.3, but I still experience a problem: 

I tested it with one phone being the Samsung s6 (Exynos SoC) running modified signal android 4.59.6 with RingRTC 1.3.3, and second phone a Huawei, with unmodified signal android 4.59.6. 

I had started a video call on my Samsung and then everything was going fine until about 30 minutes or so into the call and so my Samsung video feed crashed again. the only way I could fix it was with a restart. Before it had crashed I had tried to start another video call but when I did the camera was not being picked up and so from the Samsung phone side it appeared black. 

I had tested both times, and the same thing happened, a black screen after 30 minutes or so. Here is the debug log from the first test that I did:
https://debuglogs.org/636b5db464a366f3c21d9757bb8569a4e231818a179e7fbaecc2d78e2b618515
And then this is the debug log from the second repeated test:
https://debuglogs.org/003ce79d59dc91d0093c5956a34f5dd0003cc3af006ed8bbb5ce8ea3e5e57847
From the second one, the call started at 13:15, and ended at 13:43, I did another call at 13:47, which again resulted in a black screen due to the phone not being restarted. I would say anywhere between 27-30 minutes the call lasted and so these kind of problems started. 

I don't know if you were experiencing the same problems or did not test the Samsung s7, to such an extent but these are the kind of problems that had come out with the testing which I have done. 

I have been having the same problem with Jitsi-Meet which have also changed their Encoding to Software, but also have changed Decoding as well to it. This was also due to users complaining about their camera's not working, which as well were using Samsung. But the main difference being that it happens at a different time, I have mostly seen it happen after 40-45 minutes on a video call on Jitsi. 

I was hoping that the issue would be solved and had high hopes for it, but this took me by surprise, hopefully you can test it out and reproduce this issue on the Samsung s7 or by reading the debug logs which I have pasted here, to find the issue which is happening here and for it to be fixed. Which would enable users of such devices to be able to have video calls for how ever long they want without it freezing after a certain amount of time.

**Comment by apptester235** [comment] 2020-05-14 21:10
Experiencing the same issue on Signal android 4.60.0, have there been any updates regarding the issue, have you been able to reproduce the issue?

**Comment by jim-signal** [comment] 2020-05-15 00:10
Hi, 4.60.0 changes the calling UI, but there aren't any more fixes specific to the issues you are seeing.

So far we can't reproduce, but we are watching for it. I'll try again with some long sessions. I did see this entry in your log:

`Camera: onCameraSwitchError: switchCamera: camera is not running.`

I am not yet sure how to work around that.

**Comment by apptester235** [comment] 2020-05-15 22:48
The part that you have specified in the log was due to the Camera crashing, the video feed goes up to 30 minutes or so, the image freezes, and so then I tried to re-enable the camera, it just shows up as black or when I launch the camera app to take a photo, it says that the app has crashed because it could not find a camera. Signal itself crashes my camera when I do a live stream for 30 minutes, the only fix is to shutdown my phone and power it up again, and the camera will work, and then do a video live stream and it will crash again after 30 minutes.

**Comment by jim-signal** [comment] 2020-05-16 00:22
On my Samsung S7 with Exynos SoC, I am able to be in multiple (2!) calls for an hour, and could not reproduce the crash you are seeing. However, the phone gets really hot...

I am not sure if the crashes will show up in our debug logs... Another option is to have your phone connected to your workstation and run "adb logcat -v threadtime > my_log.txt" during the entire call, in hope of capturing the crash.

We will keep looking in to this though.

**Comment by apptester235** [comment] 2020-05-29 18:38
Hello,
I have gotten the adb logs that you requested, here is the link to them:
https://github.com/apptester235/Crash-Log/blob/master/Log
Its only a small portion of the full adb log and only shows the moment when the phone's camera crashed and the video live stream froze.

**Comment by apptester235** [comment] 2020-06-17 14:55
It seems that the issue which I am facing is a Rom issue as well as the over heating issues they are also related to it.

There is another device which is facing a video calling issue as well, I have linked the post below, 
https://community.signalusers.org/t/video-freezing-on-samsung-s6/11188/3?u=apptester234
p4nci talks about him experiencing an issue with the S10 and S10e both running a Exynose SoC, and even Samsung s9 devices as well. 

I cannot confirm if it is a Rom issue, or a signal issue and I don't know if it can be fixed by making them run on software encoding.

**Closed** 2021-03-09 21:27 UTC
